title: Vijay Jagannathan
remote_theme: carlosm2/jekyll-theme-console
style: hacker

# This creates the navigation menu in the top right
header_pages:
  - experience.md
  - skills.md
  - projects.md
  - contact.md

plugins:
  - jekyll-remote-theme
